language: objective-c
osx_image: xcode9.3
cache:
  directories:
  - $HOME/Library/Caches/org.carthage.CarthageKit/dependencies
  - Carthage
before_install:
  - ./swiftmage updateTools
  - ./swiftmage bootstrap

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  matrix:
    - CMD="testIOSDebug"
    - CMD="testIOSRelease"
    - CMD="testMacOSDebug"
    - CMD="testMacOSRelease"
    - CMD="testTVOSDebug"
    - CMD="testTVOSRelease"
    - CMD="buildWatchOSDebug"
    - CMD="buildWatchOSRelease"

script:
  - ./swiftmage $CMD

jobs:
  include:
    - stage: Pod lib lint
      script: ./swiftmage podLint

    - stage: Deploy Github
      script: skip
      before_deploy:
        - ./swiftmage buildFramework
        - ./swiftmage archiveFramework
      deploy:
        - provider: releases
          api_key:
            secure: githubkey
          file:
            - Name.framework.zip
          skip_cleanup: true
          overwrite: true
          on:
            repo: Repo/Name
            tags: true

    - stage: Deploy Cocoapods
      script: skip
      deploy:
        - provider: script
          script: ./swiftmage podPush
          skip_cleanup: true
          on:
            tags: true
